spring.application.name=courier-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:COURIER_APP}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:courier123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# HikariCP Pool settings
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

server.port=8081